### ISSUE TITLE
Add Part 2 Classes

### ISSUE THREAD

**Issue by sebbader** [eclipse-aas4j/aas4j#15]
The `model` currently contains only the classes of the AAS metamodel (aka. Part 1) but the API (aka. Part 2) also introduces further classes. One example are the `Descriptors` for the registry endpoints. I think it's reasonable to also include the Part 2 classes in this repo, maybe as another module (`model-api-classes`?) or directly in the current `model` project.

**Comment by FrankSchnicke** [comment]
I think it makes sense to add the Part 2 models in AAS4J since it fits the goal of providing the common models. I would be in favor of putting them in a 'model-api' project to keep a separation between Part 1 & Part 2.

However, there are two open points:
- Will we write these classes by hand or also auto-generate from, e.g., RDF? Is there any RDF that will be provided by Plattform Industrie 4.0 for these api models?
- If we introduce these models, we should also introduce their JSON serialization in my opinion

What do the others think?

**Comment by mjacoby** [comment]
I agree with @FrankSchnicke that we should include de-/serialization, however, this is rather complex task as there are multiple serialization formats and parameters. 

Considering the amount of work this requires I would propose to handle it as a separate work package starting after we finished updating Part 1.

**Comment by sebbader** [comment]
@mjacoby: 
> Considering the amount of work this requires I would propose to handle it as a separate work package starting after we finished updating Part 1.

Completely agreed, especially the different format variations, though only affecting JSON at the moment, give me a lot of headache.

**Comment by sebbader** [comment]
> * Will we write these classes by hand or also auto-generate from, e.g., RDF? Is there any RDF that will be provided by Plattform Industrie 4.0 for these api models?

I have an ontology and shall files for all classes available in a private branch already, so this wouldn't be a showstopper for us.

> * If we introduce these models, we should also introduce their JSON serialization in my opinion

True, we would at least need one JSON Schema file for them. Anyone knows if there is a OpenAPI-to-JSON-Schema translator out there? I have used ones for the other way (JSON Schema file to OpenAPI classes) already but never in this direction.

**Comment by twebermartins** [comment]
Note, as discussed, we decided that this ticket is relevant for V.1.0.0.

**Comment by FrankSchnicke** [comment]
Closed by https://github.com/eclipse-aas4j/aas4j/pull/161
