### ISSUE TITLE
Clearify Development/Release Process

### ISSUE THREAD

**Issue by mjacoby** [eclipse-aas4j/aas4j#32]
Follow-up ticket from https://github.com/admin-shell-io/java-serializer/pull/61

We need to clarify how the development & release process works, w.r.t. branch-naming, tagging, and release.
Previously (under admin-shell.io), a push on `main` branch triggered a maven release. Current pipeline seems to trigger a maven release when a Github release is made.
I propose changing the pipeline to trigger upon creating of a tag following the format `vX.Y.Z` and don't release on Github at all (maybe SNAPSHOTs but they can also be released via maven). 

We should also define additional things like

- How to do hot fixes, i.e. fixes an older released versions (e.g. create branch before creating a release tag and keep that branch)
- How to keep dependencies up-to-date (only for latest version or also older versions?)

**Comment by twebermartins** [comment]
Valid point! We should look for best practices in the open source community but also keeping the [Eclipse Handbook](https://www.eclipse.org/projects/handbook/#release) in mind.

I will have a look how other projects do this.

**Comment by twebermartins** [comment]
[Here](https://github.com/eclipse-digitaltwin/aas4j/blob/docs-dev_release_process/docs/adr/Development%20Process.md) are some ideas that we can discuss. 

Aft we have an agreement, we should add these processes into the [decision records](https://github.com/eclipse-digitaltwin/aas4j/blob/main/docs/adr/decision_records.md).

**Comment by mjacoby** [comment]
I have a few questions/remarks regarding the [proposed development process](https://github.com/eclipse-digitaltwin/aas4j/blob/docs-dev_release_process/docs/adr/Development%20Process.md)

![Development Process](https://github.com/eclipse-digitaltwin/aas4j/raw/docs-dev_release_process/docs/adr/branching_strategy.png)

1. change `master` to `main`
2. What is the need of having a separate `develop` branch? From my perspective there is not much advantage keeping latest features from `main`. In contrary, merging finished but unreleased features to main makes it easier for people to try out even before them being released.
3. Create release branches  not for every release but only per minor version, e.g. `release-v1.1.x`. Each release should be created as a tag. 
4. Branch housekeeping: Only permanent branches are `main`, `develop`, `release-v0.0.x`; other branches are deleted once merged.
5. How about alternative branch names besides `feature`, e.g. `bugfix` (as bugfixes != hotfixes)? I the previous projects I also regularly used something like `refactoring` for structural changes, e.g. improving code quality but also like update the CI pipeline etc.

**Comment by twebermartins** [comment]
Thanks @mjacoby 

To your points:

1. change `master` to `main`: _definitely! I just leveraged the picture as an example, but the description uses `main` instead of `master`_
2. What is the need of having a separate develop branch? From my perspective there is not much advantage keeping latest features from main. In contrary, merging finished but unreleased features to main makes it easier for people to try out even before them being released.: _I would be open for that as long all others agree on that too_
3. Create release branches not for every release but only per minor version, e.g. `release-v1.1.x`. Each release should be created as a tag.: _agree, we should integrate this point into the guidelines_
4. Branch housekeeping: Only permanent branches are main, develop, release-v0.0.x; other branches are deleted once merged.: _agreed, let's integrate this one too_
5. How about alternative branch names besides feature, e.g. bugfix (as bugfixes != hotfixes)? I the previous projects I also regularly used something like refactoring for structural changes, e.g. improving code quality but also like update the CI pipeline etc.: _I am good with you proposal_

**Comment by twebermartins** [comment]
Can we create an "example" (use case) based on our needs to understand what we need?

**Comment by twebermartins** [comment]
look: 
https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md

https://github.com/eclipse/milo

**Comment by twebermartins** [comment]
Closing issue as we agreed on [this process](https://github.com/eclipse-aas4j/aas4j/blob/main/docs/adr/development_process.md). Please reopen the issue in case it does not applies.
